version: 0.2

batch:
  fast-fail: false
  build-fanout:
    parallelism: 2
    ignore-failure: false

phases:
  install:
    commands:
      - echo 'Installing dependencies'
      - curl -s "https://get.sdkman.io" | bash
      - export SDKMAN_DIR="$HOME/.sdkman"
      - '[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ] && . "$HOME/.sdkman/bin/sdkman-init.sh"'
      - sdk install kotlin
      - curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
      - kotlinc Calculator.kt CalculatorTest.kt -d classes -cp junit-platform-console-standalone-1.8.2.jar
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Running Kotlin Tests'
      - java -jar junit-platform-console-standalone-1.8.2.jar --class-path classes --scan-class-path
  post_build:
    commands:
      - echo "Test execution completed"
