version: 0.2

batch:
  fast-fail: false
  build-fanout:
    parallelism: 2
    ignore-failure: false

phases:
  install:
    commands:
      - echo 'Installing Gradle wrapper'
      - curl -L -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar
      - ls -l gradle/wrapper/gradle-wrapper.jar
      - chmod +x gradlew
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Running Kotlin Tests'
      - |
        codebuild-tests-run \
         --test-command "./gradlew test --info" \
         --files-search "codebuild-glob-search '**/test/kotlin/*Test.kt'"
  post_build:
    commands:
      - echo "Test execution completed"
